package com.example.demo.pojo;

import java.io.Serializable;

public class Administrator implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administratorService.accounts
     *
     * @mbg.generated
     */
    private String accounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administratorService.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table administratorService
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administratorService.accounts
     *
     * @return the value of administratorService.accounts
     *
     * @mbg.generated
     */
    public String getAccounts() {
        return accounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administratorService.accounts
     *
     * @param accounts the value for administratorService.accounts
     *
     * @mbg.generated
     */
    public void setAccounts(String accounts) {
        this.accounts = accounts == null ? null : accounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administratorService.password
     *
     * @return the value of administratorService.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administratorService.password
     *
     * @param password the value for administratorService.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorService
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", accounts=").append(accounts);
        sb.append(", password=").append(password);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}