package com.example.demo.pojo;

import java.io.Serializable;

public class Categories implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.test_categories
     *
     * @mbg.generated
     */
    private String testCategories;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table categories
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.id
     *
     * @return the value of categories.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.id
     *
     * @param id the value for categories.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.test_categories
     *
     * @return the value of categories.test_categories
     *
     * @mbg.generated
     */
    public String getTestCategories() {
        return testCategories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.test_categories
     *
     * @param testCategories the value for categories.test_categories
     *
     * @mbg.generated
     */
    public void setTestCategories(String testCategories) {
        this.testCategories = testCategories == null ? null : testCategories.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", testCategories=").append(testCategories);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}