package com.example.demo.pojo;

public class Cet6 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.student_number
     *
     * @mbg.generated
     */
    private String studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.school_name
     *
     * @mbg.generated
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.shool_code
     *
     * @mbg.generated
     */
    private String shoolCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.room_number
     *
     * @mbg.generated
     */
    private String roomNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.seat_number
     *
     * @mbg.generated
     */
    private String seatNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.student_name
     *
     * @mbg.generated
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.exam_number
     *
     * @mbg.generated
     */
    private String examNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.classroom
     *
     * @mbg.generated
     */
    private String classroom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.time
     *
     * @mbg.generated
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.quantum
     *
     * @mbg.generated
     */
    private String quantum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet4.rule
     *
     * @mbg.generated
     */
    private String rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cet4
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.student_number
     *
     * @return the value of cet4.student_number
     *
     * @mbg.generated
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.student_number
     *
     * @param studentNumber the value for cet4.student_number
     *
     * @mbg.generated
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber == null ? null : studentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.school_name
     *
     * @return the value of cet4.school_name
     *
     * @mbg.generated
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.school_name
     *
     * @param schoolName the value for cet4.school_name
     *
     * @mbg.generated
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.shool_code
     *
     * @return the value of cet4.shool_code
     *
     * @mbg.generated
     */
    public String getShoolCode() {
        return shoolCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.shool_code
     *
     * @param shoolCode the value for cet4.shool_code
     *
     * @mbg.generated
     */
    public void setShoolCode(String shoolCode) {
        this.shoolCode = shoolCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.room_number
     *
     * @return the value of cet4.room_number
     *
     * @mbg.generated
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.room_number
     *
     * @param roomNumber the value for cet4.room_number
     *
     * @mbg.generated
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.seat_number
     *
     * @return the value of cet4.seat_number
     *
     * @mbg.generated
     */
    public String getSeatNumber() {
        return seatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.seat_number
     *
     * @param seatNumber the value for cet4.seat_number
     *
     * @mbg.generated
     */
    public void setSeatNumber(String seatNumber) {
        this.seatNumber = seatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.student_name
     *
     * @return the value of cet4.student_name
     *
     * @mbg.generated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.student_name
     *
     * @param studentName the value for cet4.student_name
     *
     * @mbg.generated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.class_name
     *
     * @return the value of cet4.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.class_name
     *
     * @param className the value for cet4.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.exam_number
     *
     * @return the value of cet4.exam_number
     *
     * @mbg.generated
     */
    public String getExamNumber() {
        return examNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.exam_number
     *
     * @param examNumber the value for cet4.exam_number
     *
     * @mbg.generated
     */
    public void setExamNumber(String examNumber) {
        this.examNumber = examNumber == null ? null : examNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.classroom
     *
     * @return the value of cet4.classroom
     *
     * @mbg.generated
     */
    public String getClassroom() {
        return classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.classroom
     *
     * @param classroom the value for cet4.classroom
     *
     * @mbg.generated
     */
    public void setClassroom(String classroom) {
        this.classroom = classroom == null ? null : classroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.time
     *
     * @return the value of cet4.time
     *
     * @mbg.generated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.time
     *
     * @param time the value for cet4.time
     *
     * @mbg.generated
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.quantum
     *
     * @return the value of cet4.quantum
     *
     * @mbg.generated
     */
    public String getQuantum() {
        return quantum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.quantum
     *
     * @param quantum the value for cet4.quantum
     *
     * @mbg.generated
     */
    public void setQuantum(String quantum) {
        this.quantum = quantum == null ? null : quantum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet4.rule
     *
     * @return the value of cet4.rule
     *
     * @mbg.generated
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet4.rule
     *
     * @param rule the value for cet4.rule
     *
     * @mbg.generated
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet4
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studentNumber=").append(studentNumber);
        sb.append(", schoolName=").append(schoolName);
        sb.append(", shoolCode=").append(shoolCode);
        sb.append(", roomNumber=").append(roomNumber);
        sb.append(", seatNumber=").append(seatNumber);
        sb.append(", studentName=").append(studentName);
        sb.append(", className=").append(className);
        sb.append(", examNumber=").append(examNumber);
        sb.append(", classroom=").append(classroom);
        sb.append(", time=").append(time);
        sb.append(", quantum=").append(quantum);
        sb.append(", rule=").append(rule);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
