package com.example.demo.dao;

import com.example.demo.pojo.Cet4;
import com.example.demo.pojo.Cet6;
import com.example.demo.pojo.result.cet4;
import com.example.demo.pojo.result.cet6;

import java.util.List;

public interface Cet6Mapper {

    int insert(Cet6 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet4
     *
     * @mbg.generated
     */
    cet6 selectByPrimaryKey(String studentNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet4
     *
     * @mbg.generated
     */
    List<Cet6> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cet4
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cet6 record);


    int selectByStudentNumber(String number);
}
