package com.example.demo.dao;

import com.example.demo.pojo.Pictures;
import java.util.List;

public interface PicturesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String studentNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbg.generated
     */
    int insert(Pictures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbg.generated
     */
    Pictures selectByPrimaryKey(String studentNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbg.generated
     */
    List<Pictures> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pictures record);
}