package com.example.demo.dao;

import com.example.demo.pojo.Time;
import java.util.List;

public interface TimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String category);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int insert(Time record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    Time selectByPrimaryKey(String category);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    List<Time> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Time record);
}